/** Shared color alias map + normalizer (used by recommendationEngine + intentScoring). */

const COLOR_ALIASES = {
  navy: 'Blue',
  'navy blue': 'Blue',
  'sky blue': 'Blue',
  cobalt: 'Blue',
  'royal blue': 'Blue',
  'light blue': 'Blue',
  'powder blue': 'Blue',
  'steel blue': 'Blue',
  'pastel blue': 'Blue',
  'dark blue': 'Blue',
  'deep blue': 'Blue',
  'midnight blue': 'Blue',
  'electric blue': 'Blue',
  'baby blue': 'Blue',
  'prussian blue': 'Blue',
  cerulean: 'Blue',
  azure: 'Blue',
  denim: 'Blue',
  indigo: 'Blue',
  nila: 'Blue',
  emerald: 'Green',
  olive: 'Green',
  mint: 'Green',
  sage: 'Green',
  'forest green': 'Green',
  'bottle green': 'Green',
  'sea green': 'Green',
  'dark green': 'Green',
  'deep green': 'Green',
  'mehendi green': 'Green',
  'mint green': 'Green',
  'lime green': 'Green',
  lime: 'Green',
  pista: 'Green',
  pistachio: 'Green',
  'apple green': 'Green',
  'jungle green': 'Green',
  'hunter green': 'Green',
  'kelly green': 'Green',
  'army green': 'Green',
  'military green': 'Green',
  forest: 'Green',
  'neon green': 'Green',
  'grass green': 'Green',
  'parrot green': 'Green',
  dhani: 'Green',
  mehendi: 'Green',
  sabz: 'Green',
  maroon: 'Red',
  crimson: 'Red',
  burgundy: 'Red',
  wine: 'Red',
  rust: 'Red',
  'dark red': 'Red',
  'deep red': 'Red',
  'brick red': 'Red',
  'dark maroon': 'Red',
  'deep maroon': 'Red',
  'dark burgundy': 'Red',
  cherry: 'Red',
  cardinal: 'Red',
  scarlet: 'Red',
  ruby: 'Red',
  raspberry: 'Red',
  strawberry: 'Red',
  'blood red': 'Red',
  mehroon: 'Red',
  mehrun: 'Red',
  merun: 'Red',
  surkh: 'Red',
  laal: 'Red',
  beige: 'Beige',
  nude: 'Beige',
  camel: 'Beige',
  fawn: 'Beige',
  khaki: 'Beige',
  khaaki: 'Beige',
  sand: 'Beige',
  oat: 'Beige',
  linen: 'Beige',
  biscuit: 'Beige',
  wheat: 'Beige',
  taupe: 'Beige',
  'nude beige': 'Beige',
  'warm beige': 'Beige',
  natural: 'Beige',
  ivory: 'White',
  cream: 'White',
  'off white': 'White',
  'off-white': 'White',
  snow: 'White',
  pearl: 'White',
  chalk: 'White',
  'milk white': 'White',
  'pure white': 'White',
  'bright white': 'White',
  'warm white': 'White',
  eggshell: 'White',
  'antique white': 'White',
  safed: 'White',
  silver: 'Grey',
  ash: 'Grey',
  'steel grey': 'Grey',
  slate: 'Grey',
  stone: 'Grey',
  smoke: 'Grey',
  gray: 'Grey',
  grey: 'Grey',
  'light grey': 'Grey',
  'dark grey': 'Grey',
  'steel gray': 'Grey',
  platinum: 'Grey',
  gunmetal: 'Grey',
  'charcoal grey': 'Grey',
  'warm grey': 'Grey',
  'cool grey': 'Grey',
  'dove grey': 'Grey',
  charcoal: 'Black',
  graphite: 'Black',
  onyx: 'Black',
  ebony: 'Black',
  'jet black': 'Black',
  'pitch black': 'Black',
  'off black': 'Black',
  blush: 'Pink',
  peach: 'Pink',
  rose: 'Pink',
  fuchsia: 'Pink',
  'hot pink': 'Pink',
  'dusty pink': 'Pink',
  'baby pink': 'Pink',
  'nude pink': 'Pink',
  'pastel pink': 'Pink',
  'dusty rose': 'Pink',
  'old rose': 'Pink',
  'candy pink': 'Pink',
  'shocking pink': 'Pink',
  'light pink': 'Pink',
  'deep pink': 'Pink',
  salmon: 'Pink',
  magenta: 'Pink',
  cerise: 'Pink',
  flamingo: 'Pink',
  carnation: 'Pink',
  'blush pink': 'Pink',
  'rose pink': 'Pink',
  bubblegum: 'Pink',
  'millennial pink': 'Pink',
  'macaroon pink': 'Pink',
  gulabi: 'Pink',
  lavender: 'Purple',
  lilac: 'Purple',
  mauve: 'Purple',
  plum: 'Purple',
  violet: 'Purple',
  grape: 'Purple',
  wisteria: 'Purple',
  'pastel purple': 'Purple',
  'light purple': 'Purple',
  'deep purple': 'Purple',
  'dark purple': 'Purple',
  'royal purple': 'Purple',
  'dusty purple': 'Purple',
  amethyst: 'Purple',
  orchid: 'Purple',
  heather: 'Purple',
  periwinkle: 'Purple',
  jamuni: 'Purple',
  baingan: 'Purple',
  coral: 'Orange',
  terracotta: 'Orange',
  amber: 'Orange',
  'burnt orange': 'Orange',
  'peach orange': 'Orange',
  apricot: 'Orange',
  pumpkin: 'Orange',
  tangerine: 'Orange',
  mango: 'Orange',
  'deep orange': 'Orange',
  'burnt sienna': 'Orange',
  copper: 'Orange',
  narangi: 'Orange',
  mustard: 'Yellow',
  lemon: 'Yellow',
  saffron: 'Yellow',
  'lemon yellow': 'Yellow',
  'pastel yellow': 'Yellow',
  butter: 'Yellow',
  canary: 'Yellow',
  sunflower: 'Yellow',
  'golden yellow': 'Yellow',
  'bright yellow': 'Yellow',
  'neon yellow': 'Yellow',
  chartreuse: 'Yellow',
  ochre: 'Yellow',
  corn: 'Yellow',
  honey: 'Yellow',
  zard: 'Yellow',
  peela: 'Yellow',
  golden: 'Gold',
  gold: 'Gold',
  'antique gold': 'Gold',
  'dull gold': 'Gold',
  champagne: 'Gold',
  bronze: 'Gold',
  brass: 'Gold',
  'metallic gold': 'Gold',
  'light gold': 'Gold',
  'rose gold': 'Gold',
  turquoise: 'Teal',
  aqua: 'Teal',
  cyan: 'Teal',
  seafoam: 'Teal',
  'teal green': 'Teal',
  'dark teal': 'Teal',
  'deep teal': 'Teal',
  'teal blue': 'Teal',
  peacock: 'Teal',
  'peacock blue': 'Teal',
  ferozi: 'Teal',
  firozi: 'Teal',
  chocolate: 'Brown',
  mocha: 'Brown',
  coffee: 'Brown',
  caramel: 'Brown',
  tan: 'Brown',
  walnut: 'Brown',
  toffee: 'Brown',
  chestnut: 'Brown',
  'dark brown': 'Brown',
  'light brown': 'Brown',
  mahogany: 'Brown',
  sienna: 'Brown',
  sepia: 'Brown',
  hazel: 'Brown',
  cocoa: 'Brown',
  'saddle brown': 'Brown',
  'raw umber': 'Brown',
  multi: 'Multicolor',
  multicolor: 'Multicolor',
  'multi-color': 'Multicolor',
  'multi colour': 'Multicolor',
  multicolour: 'Multicolor',
  printed: 'Multicolor',
  colourful: 'Multicolor',
  colorful: 'Multicolor',
  floral: 'Multicolor',
  patterned: 'Multicolor',
  geometric: 'Multicolor',
  abstract: 'Multicolor',
  'tie dye': 'Multicolor',
  ombre: 'Multicolor'
};

export function normalizeColor(color) {
  if (!color) return null;
  const lower = color.toLowerCase().trim();
  if (COLOR_ALIASES[lower]) return COLOR_ALIASES[lower];
  return color.charAt(0).toUpperCase() + color.slice(1).toLowerCase();
}
