import { inferColors } from './scripts/scrapers/utils/colorInference.js';
import { normalizeProduct } from './scripts/scrapers/parsers/productParser.js';
console.log('COLOR (Multicolor deprioritized):');
console.log(' Cosmos Blue + variant Multi:', JSON.stringify(inferColors({ options:'Multi', title:'3 PIECE PRINTED LAWN SUIT-COSMOS BLUE', tags:'', description:'digital print' })));
console.log(' pure floral, no color   :', JSON.stringify(inferColors({ options:'Multi', title:'Floral Fantasy Printed Suit', tags:'', description:'multi floral' })));
console.log(' variant Green vs title Coral:', JSON.stringify(inferColors({ options:'Green', title:'Coral Reef Printed Lawn', tags:'', description:'' })));
console.log('\nFABRIC (title-first):');
const bc = (sub) => ({ brand:'Beechtree', category:'clothing', subCategory: sub, occasion:['party'], style:[], source:'t' });
const p = normalizeProduct({ title:'2 PIECE EMBROIDERED KHADDAR SUIT (LUXURY PRET)', description:'luxurious silky drape finish', tags:['Women'], variantOptions:['Maroon'], images:['x'], productUrl:'http://a/1', price: 8000 }, bc('2-piece'));
console.log(' KHADDAR SUIT (desc says silky):', p.fabric);
