import dotenv from 'dotenv'; import path from 'path';
dotenv.config({ path: path.resolve('.env') });
import connectDB from './config/db.js';
import Clothing from './models/ClothingProduct.js';
import Shoe from './models/ShoeProduct.js';
await connectDB();
const cCount = await Clothing.estimatedDocumentCount();
const sCount = await Shoe.estimatedDocumentCount();
const cGender = await Clothing.aggregate([{$group:{_id:'$gender',n:{$sum:1}}}]);
const sGender = await Shoe.aggregate([{$group:{_id:'$gender',n:{$sum:1}}}]);
const cColor = await Clothing.aggregate([{$group:{_id:'$primaryColor',n:{$sum:1}}},{$sort:{n:-1}}]);
const sColor = await Shoe.aggregate([{$group:{_id:'$primaryColor',n:{$sum:1}}},{$sort:{n:-1}}]);
console.log('Clothing total:', cCount, 'gender:', JSON.stringify(cGender));
console.log('Shoe total:', sCount, 'gender:', JSON.stringify(sGender));
console.log('Clothing primaryColor dist:', JSON.stringify(cColor));
console.log('Shoe primaryColor dist:', JSON.stringify(sColor));
process.exit(0);
